#!/usr/bin/env bash
# Installed Nginx in our server
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > index.html
sudo mv index.html /var/www/html/
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
