#!/usr/bin/env bash
# Loop while with case statement
i=1
while [ $i -le 20 ]
do
    echo $i
case $i in
    4)
        echo bad luck from China
        ;;
    9)
        echo bad luck from Japan
        ;;
    17)
        echo ad luck from Italy
        ;;
esac
((i++))
done
